Add DSS example 2 code
karak-network/DSS-Templates pull request #8
Opened 2024-09-26 16:31 UTC by chaitAtAndalusia

2024-09-30 14:04 UTC, krustaceany requested changes

2024-09-30 14:04 UTC, krustaceany commented on square-number-bls/aggregator/src/task.rs
> +        }
I feel this should be done asynchronously, ie, the post request should be spawned and added to a handle vector. you can then join all the handles later. otherwise, you'll always end up going sequentially through each operator

2024-09-30 14:04 UTC, krustaceany commented on square-number-bls/aggregator/src/task.rs
> +        }
also, are we allowing operators to timeout? perhaps having a deadline for responses might be a good idea? @rishabh-vasudevan19 wdyt?

2024-10-01 15:32 UTC, rishabh-vasudevan19 commented on square-number-bls/aggregator/src/task.rs
> +        }
Yeah I think we could add that. And I think we should discuss a little more of what we expect of the template. Because initially it was supposed to be an example of how everything interacts. But now it has become more a template that can be used directly.

2024-10-01 15:32 UTC, rishabh-vasudevan19 commented on square-number-bls/aggregator/src/task.rs
> +            .ok_or(TaskError::TaskVerificationFailed)?;
Hmm I think we could define a criteria of which response is first. Or failing is also fine

2024-10-02 12:15 UTC, krustaceany approved these changes

2024-10-02 14:06 UTC, merged